apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudvisor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cloudvisor.labels" . | indent 4 }}
data:
  VPC_ID: {{ .Values.aws.config.vpcId | quote }}
  SUBNET_IDS: {{ join " " .Values.aws.config.subnetIds | quote }}
  KEY_PAIR_ID: {{ .Values.aws.config.keyPairId | quote }}
  SERVICE_PORT: {{ .Values.service.port | quote }}
  HABERTEST_PROVISIONER_ADDRESS: {{ .Values.provisionerAddress | quote }}
<<<<<<< HEAD
=======
  {{ if not .Values.aws.config.secretName }}
  AWS_DEFAULT_REGION: {{  .Values.aws.config.defaultRegion | quote }}
  {{ end }}
>>>>>>> wip
