{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cloudvisor.serviceAccountName" . }}
  labels:
{{ include "cloudvisor.labels" . | indent 4 }}
{{- end -}}
