apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "provisioner.labels" . | indent 4 }}
data:
  REDIS_HOST: "{{ .Values.redis.host }}"
  REDIS_PORT: "{{ .Values.redis.port }}"
  REDIS_DB: "{{ .Values.redis.db }}"
  REDIS_USER: "{{ .Values.redis.user }}"
  REDIS_PASSWORD: "{{ .Values.redis.password }}"
