{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "provisioner.serviceAccountName" . }}
  labels:
{{ include "provisioner.labels" . | indent 4 }}
{{- end -}}
