# docker build -t cloudvisor -f Dockerfile.cloudvisor .

FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    curl python3.8 python3-pip python3.8-dev vim

RUN ln -sf -T /usr/bin/python3.8 /usr/bin/python

COPY  ./requirements3.txt /tmp/requirements3.txt
RUN python -m pip install -r /tmp/requirements3.txt \
    && rm /tmp/requirements3.txt


COPY . /root/resource_managers
WORKDIR /root/resource_managers

CMD python -m cloudvisor
