---
version: "3.7"
services:
  allocate:
    image: anyvision-hwprovisioner-allocate
    build:
      context: provisioner
      dockerfile: provisioner/Dockerfile
    volumes:
      - ./provisioner:/src
    ports:
      - 8080:8080
    environment:
      - REDIS_USER=guest
      - REDIS_PASSWORD=pAssw0Rd!
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    restart: always
    depends_on:
      - redis
    working_dir: /src
    command: watchmedo auto-restart --patterns="*.py;*.yaml;*.yml" --recursive -- python -m 'webapp.app' serve
  heartbeats:
    image: anyvision-hwprovisioner-heartbeats
    build:
      context: heartbeat_server
      dockerfile: heartbeat_server/Dockerfile
    volumes:
      - ./heartbeat_server:/src
    ports:
      - 7080:8080
    environment:
      - REDIS_USER=guest
      - REDIS_PASSWORD=pAssw0Rd!
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    restart: always
    depends_on:
      - redis
    command: watchmedo auto-restart --patterns="*.py;*.yaml;*.yml" --recursive -- python -m 'webapp.app' serve
  redis:
    image: redis:5.0.7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    restart: always
    ports:
      - 6379:6379
